// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

package buzz.giiiiiv.gift;

public final class Req {
    private Req() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface PbOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Pb)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 a = 1;</code>
         * @return The a.
         */
        int getA();

        /**
         * <code>string b = 2;</code>
         * @return The b.
         */
        java.lang.String getB();
        /**
         * <code>string b = 2;</code>
         * @return The bytes for b.
         */
        com.google.protobuf.ByteString
        getBBytes();

        /**
         * <code>string c = 3;</code>
         * @return The c.
         */
        java.lang.String getC();
        /**
         * <code>string c = 3;</code>
         * @return The bytes for c.
         */
        com.google.protobuf.ByteString
        getCBytes();

        /**
         * <code>int32 d = 4;</code>
         * @return The d.
         */
        int getD();

        /**
         * <code>int32 e = 5;</code>
         * @return The e.
         */
        int getE();

        /**
         * <code>int32 f = 6;</code>
         * @return The f.
         */
        int getF();

        /**
         * <code>string g = 9;</code>
         * @return The g.
         */
        java.lang.String getG();
        /**
         * <code>string g = 9;</code>
         * @return The bytes for g.
         */
        com.google.protobuf.ByteString
        getGBytes();
    }
    /**
     * Protobuf type {@code Pb}
     */
    public static final class Pb extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Pb)
            PbOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Pb.newBuilder() to construct.
        private Pb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Pb() {
            b_ = "";
            c_ = "";
            g_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Pb();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Pb(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            a_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            b_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            c_ = s;
                            break;
                        }
                        case 32: {

                            d_ = input.readInt32();
                            break;
                        }
                        case 40: {

                            e_ = input.readInt32();
                            break;
                        }
                        case 48: {

                            f_ = input.readInt32();
                            break;
                        }
                        case 74: {
                            java.lang.String s = input.readStringRequireUtf8();

                            g_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return buzz.giiiiiv.gift.Req.internal_static_Pb_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return buzz.giiiiiv.gift.Req.internal_static_Pb_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            buzz.giiiiiv.gift.Req.Pb.class, buzz.giiiiiv.gift.Req.Pb.Builder.class);
        }

        public static final int A_FIELD_NUMBER = 1;
        private int a_;
        /**
         * <code>int32 a = 1;</code>
         * @return The a.
         */
        @java.lang.Override
        public int getA() {
            return a_;
        }

        public static final int B_FIELD_NUMBER = 2;
        private volatile java.lang.Object b_;
        /**
         * <code>string b = 2;</code>
         * @return The b.
         */
        @java.lang.Override
        public java.lang.String getB() {
            java.lang.Object ref = b_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                b_ = s;
                return s;
            }
        }
        /**
         * <code>string b = 2;</code>
         * @return The bytes for b.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getBBytes() {
            java.lang.Object ref = b_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                b_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int C_FIELD_NUMBER = 3;
        private volatile java.lang.Object c_;
        /**
         * <code>string c = 3;</code>
         * @return The c.
         */
        @java.lang.Override
        public java.lang.String getC() {
            java.lang.Object ref = c_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                c_ = s;
                return s;
            }
        }
        /**
         * <code>string c = 3;</code>
         * @return The bytes for c.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getCBytes() {
            java.lang.Object ref = c_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                c_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int D_FIELD_NUMBER = 4;
        private int d_;
        /**
         * <code>int32 d = 4;</code>
         * @return The d.
         */
        @java.lang.Override
        public int getD() {
            return d_;
        }

        public static final int E_FIELD_NUMBER = 5;
        private int e_;
        /**
         * <code>int32 e = 5;</code>
         * @return The e.
         */
        @java.lang.Override
        public int getE() {
            return e_;
        }

        public static final int F_FIELD_NUMBER = 6;
        private int f_;
        /**
         * <code>int32 f = 6;</code>
         * @return The f.
         */
        @java.lang.Override
        public int getF() {
            return f_;
        }

        public static final int G_FIELD_NUMBER = 9;
        private volatile java.lang.Object g_;
        /**
         * <code>string g = 9;</code>
         * @return The g.
         */
        @java.lang.Override
        public java.lang.String getG() {
            java.lang.Object ref = g_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                g_ = s;
                return s;
            }
        }
        /**
         * <code>string g = 9;</code>
         * @return The bytes for g.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getGBytes() {
            java.lang.Object ref = g_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                g_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (a_ != 0) {
                output.writeInt32(1, a_);
            }
            if (!getBBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, b_);
            }
            if (!getCBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, c_);
            }
            if (d_ != 0) {
                output.writeInt32(4, d_);
            }
            if (e_ != 0) {
                output.writeInt32(5, e_);
            }
            if (f_ != 0) {
                output.writeInt32(6, f_);
            }
            if (!getGBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, g_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (a_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, a_);
            }
            if (!getBBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, b_);
            }
            if (!getCBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, c_);
            }
            if (d_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, d_);
            }
            if (e_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, e_);
            }
            if (f_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, f_);
            }
            if (!getGBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, g_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof buzz.giiiiiv.gift.Req.Pb)) {
                return super.equals(obj);
            }
            buzz.giiiiiv.gift.Req.Pb other = (buzz.giiiiiv.gift.Req.Pb) obj;

            if (getA()
                    != other.getA()) return false;
            if (!getB()
                    .equals(other.getB())) return false;
            if (!getC()
                    .equals(other.getC())) return false;
            if (getD()
                    != other.getD()) return false;
            if (getE()
                    != other.getE()) return false;
            if (getF()
                    != other.getF()) return false;
            if (!getG()
                    .equals(other.getG())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + A_FIELD_NUMBER;
            hash = (53 * hash) + getA();
            hash = (37 * hash) + B_FIELD_NUMBER;
            hash = (53 * hash) + getB().hashCode();
            hash = (37 * hash) + C_FIELD_NUMBER;
            hash = (53 * hash) + getC().hashCode();
            hash = (37 * hash) + D_FIELD_NUMBER;
            hash = (53 * hash) + getD();
            hash = (37 * hash) + E_FIELD_NUMBER;
            hash = (53 * hash) + getE();
            hash = (37 * hash) + F_FIELD_NUMBER;
            hash = (53 * hash) + getF();
            hash = (37 * hash) + G_FIELD_NUMBER;
            hash = (53 * hash) + getG().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static buzz.giiiiiv.gift.Req.Pb parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(buzz.giiiiiv.gift.Req.Pb prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Pb}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Pb)
                buzz.giiiiiv.gift.Req.PbOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return buzz.giiiiiv.gift.Req.internal_static_Pb_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return buzz.giiiiiv.gift.Req.internal_static_Pb_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                buzz.giiiiiv.gift.Req.Pb.class, buzz.giiiiiv.gift.Req.Pb.Builder.class);
            }

            // Construct using buzz.giiiiiv.gift.Req.Pb.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                a_ = 0;

                b_ = "";

                c_ = "";

                d_ = 0;

                e_ = 0;

                f_ = 0;

                g_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return buzz.giiiiiv.gift.Req.internal_static_Pb_descriptor;
            }

            @java.lang.Override
            public buzz.giiiiiv.gift.Req.Pb getDefaultInstanceForType() {
                return buzz.giiiiiv.gift.Req.Pb.getDefaultInstance();
            }

            @java.lang.Override
            public buzz.giiiiiv.gift.Req.Pb build() {
                buzz.giiiiiv.gift.Req.Pb result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public buzz.giiiiiv.gift.Req.Pb buildPartial() {
                buzz.giiiiiv.gift.Req.Pb result = new buzz.giiiiiv.gift.Req.Pb(this);
                result.a_ = a_;
                result.b_ = b_;
                result.c_ = c_;
                result.d_ = d_;
                result.e_ = e_;
                result.f_ = f_;
                result.g_ = g_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof buzz.giiiiiv.gift.Req.Pb) {
                    return mergeFrom((buzz.giiiiiv.gift.Req.Pb)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(buzz.giiiiiv.gift.Req.Pb other) {
                if (other == buzz.giiiiiv.gift.Req.Pb.getDefaultInstance()) return this;
                if (other.getA() != 0) {
                    setA(other.getA());
                }
                if (!other.getB().isEmpty()) {
                    b_ = other.b_;
                    onChanged();
                }
                if (!other.getC().isEmpty()) {
                    c_ = other.c_;
                    onChanged();
                }
                if (other.getD() != 0) {
                    setD(other.getD());
                }
                if (other.getE() != 0) {
                    setE(other.getE());
                }
                if (other.getF() != 0) {
                    setF(other.getF());
                }
                if (!other.getG().isEmpty()) {
                    g_ = other.g_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                buzz.giiiiiv.gift.Req.Pb parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (buzz.giiiiiv.gift.Req.Pb) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int a_ ;
            /**
             * <code>int32 a = 1;</code>
             * @return The a.
             */
            @java.lang.Override
            public int getA() {
                return a_;
            }
            /**
             * <code>int32 a = 1;</code>
             * @param value The a to set.
             * @return This builder for chaining.
             */
            public Builder setA(int value) {

                a_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 a = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearA() {

                a_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object b_ = "";
            /**
             * <code>string b = 2;</code>
             * @return The b.
             */
            public java.lang.String getB() {
                java.lang.Object ref = b_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    b_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string b = 2;</code>
             * @return The bytes for b.
             */
            public com.google.protobuf.ByteString
            getBBytes() {
                java.lang.Object ref = b_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    b_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string b = 2;</code>
             * @param value The b to set.
             * @return This builder for chaining.
             */
            public Builder setB(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                b_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string b = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearB() {

                b_ = getDefaultInstance().getB();
                onChanged();
                return this;
            }
            /**
             * <code>string b = 2;</code>
             * @param value The bytes for b to set.
             * @return This builder for chaining.
             */
            public Builder setBBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                b_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object c_ = "";
            /**
             * <code>string c = 3;</code>
             * @return The c.
             */
            public java.lang.String getC() {
                java.lang.Object ref = c_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    c_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string c = 3;</code>
             * @return The bytes for c.
             */
            public com.google.protobuf.ByteString
            getCBytes() {
                java.lang.Object ref = c_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    c_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string c = 3;</code>
             * @param value The c to set.
             * @return This builder for chaining.
             */
            public Builder setC(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                c_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string c = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearC() {

                c_ = getDefaultInstance().getC();
                onChanged();
                return this;
            }
            /**
             * <code>string c = 3;</code>
             * @param value The bytes for c to set.
             * @return This builder for chaining.
             */
            public Builder setCBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                c_ = value;
                onChanged();
                return this;
            }

            private int d_ ;
            /**
             * <code>int32 d = 4;</code>
             * @return The d.
             */
            @java.lang.Override
            public int getD() {
                return d_;
            }
            /**
             * <code>int32 d = 4;</code>
             * @param value The d to set.
             * @return This builder for chaining.
             */
            public Builder setD(int value) {

                d_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 d = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearD() {

                d_ = 0;
                onChanged();
                return this;
            }

            private int e_ ;
            /**
             * <code>int32 e = 5;</code>
             * @return The e.
             */
            @java.lang.Override
            public int getE() {
                return e_;
            }
            /**
             * <code>int32 e = 5;</code>
             * @param value The e to set.
             * @return This builder for chaining.
             */
            public Builder setE(int value) {

                e_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 e = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearE() {

                e_ = 0;
                onChanged();
                return this;
            }

            private int f_ ;
            /**
             * <code>int32 f = 6;</code>
             * @return The f.
             */
            @java.lang.Override
            public int getF() {
                return f_;
            }
            /**
             * <code>int32 f = 6;</code>
             * @param value The f to set.
             * @return This builder for chaining.
             */
            public Builder setF(int value) {

                f_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 f = 6;</code>
             * @return This builder for chaining.
             */
            public Builder clearF() {

                f_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object g_ = "";
            /**
             * <code>string g = 9;</code>
             * @return The g.
             */
            public java.lang.String getG() {
                java.lang.Object ref = g_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    g_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string g = 9;</code>
             * @return The bytes for g.
             */
            public com.google.protobuf.ByteString
            getGBytes() {
                java.lang.Object ref = g_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    g_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string g = 9;</code>
             * @param value The g to set.
             * @return This builder for chaining.
             */
            public Builder setG(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                g_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string g = 9;</code>
             * @return This builder for chaining.
             */
            public Builder clearG() {

                g_ = getDefaultInstance().getG();
                onChanged();
                return this;
            }
            /**
             * <code>string g = 9;</code>
             * @param value The bytes for g to set.
             * @return This builder for chaining.
             */
            public Builder setGBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                g_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Pb)
        }

        // @@protoc_insertion_point(class_scope:Pb)
        private static final buzz.giiiiiv.gift.Req.Pb DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new buzz.giiiiiv.gift.Req.Pb();
        }

        public static buzz.giiiiiv.gift.Req.Pb getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Pb>
                PARSER = new com.google.protobuf.AbstractParser<Pb>() {
            @java.lang.Override
            public Pb parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Pb(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Pb> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Pb> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public buzz.giiiiiv.gift.Req.Pb getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Pb_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Pb_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\010my.proto\"Q\n\002Pb\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\t\022\t" +
                        "\n\001c\030\003 \001(\t\022\t\n\001d\030\004 \001(\005\022\t\n\001e\030\005 \001(\005\022\t\n\001f\030\006 \001" +
                        "(\005\022\t\n\001g\030\t \001(\tB\030\n\021buzz.giiiiiv.giftB\003Reqb" +
                        "\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_Pb_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Pb_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Pb_descriptor,
                new java.lang.String[] { "A", "B", "C", "D", "E", "F", "G", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
